<a href="https://colab.research.google.com/github/varnitjain8822/MACHINE-LEARNING-PROJECTS/blob/main/sentimant_analysis_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [6]:
df=pd.read_csv('train.txt',sep=';',names=['text','emotion'])
df.head()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [7]:
unique_emotion=df['emotion'].unique()

In [8]:
emotion_numbers={}
i=0
for emo in unique_emotion:
  emotion_numbers[emo]=i
  i=i+1
emotion_numbers


{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [9]:
df['emotion']=df['emotion'].map(emotion_numbers)

In [11]:
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [12]:
df['text']=df['text'].apply(lambda x : x.lower())

In [17]:
#removing punctuation
import string
def remove_pun(text):
  return text.translate(str.maketrans('','',string.punctuation))


In [19]:
df['text']=df['text'].apply(remove_pun)

In [20]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [21]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [22]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [23]:
stop_words = set(stopwords.words('english'))

In [26]:
def remove(txt):
  words = word_tokenize(txt)  #txt.spli()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [28]:
import nltk
nltk.download('punkt_tab')
df['text']=df['text'].apply(remove)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [36]:
# bag of word technique of vetorization

from sklearn.feature_extraction.text import CountVectorizer

document=['i love pizza','i love coldrink','i love burger']

vectorizer=CountVectorizer(ngram_range=(1,2))
X=vectorizer.fit_transform(document)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['burger' 'coldrink' 'love' 'love burger' 'love coldrink' 'love pizza'
 'pizza']
[[0 0 1 0 0 1 1]
 [0 1 1 0 1 0 0]
 [1 0 1 1 0 0 0]]


In [38]:
# bag of word technique of vetorization

from sklearn.feature_extraction.text import TfidfVectorizer

document=['i love pizza','i love coldrink','i love burger']

vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(document)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['burger' 'coldrink' 'love' 'pizza']
[[0.         0.         0.50854232 0.861037  ]
 [0.         0.861037   0.50854232 0.        ]
 [0.861037   0.         0.50854232 0.        ]]


In [39]:
df

,text,emotion
0,didnt feel humiliated,0
1,go feeling hopeless damned hopeful around some...,0
2,im grabbing minute post feel greedy wrong,1
3,ever feeling nostalgic fireplace know still pr...,2
4,feeling grouchy,1
...,...,...
15995,brief time beanbag said anna feel like beaten,0
15996,turning feel pathetic still waiting tables sub...,0
15997,feel strong good overall,5
15998,feel like rude comment im glad,1


In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['emotion'],test_size=0.2,random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer
vectorizer=TfidfVectorizer()
X_train_idfd=vectorizer.fit_transform(X_train)
X_test_idfd=vectorizer.fit_transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
model=MultinomialNB()
model.fit(X_train_idfd,y_train)

MultinomialNB()

In [52]:
#  tfidf with naive baies
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

X_train_idfd = vectorizer.fit_transform(X_train)
X_test_idfd = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_idfd, y_train)

ypred = model.predict(X_test_idfd)
print(accuracy_score(y_test,ypred))

0.6609375


In [55]:
# bag of words with countvectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
vectorizer = CountVectorizer()
X_train_bow = vectorizer.fit_transform(X_train)
X_test_bow = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_bow, y_train)

ypred = model.predict(X_test_bow)
print(accuracy_score(y_test,ypred))

0.7678125


In [60]:
# tfidf with logistic regression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

ypred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, ypred))


Accuracy: 0.8615625
